### PR TITLE
Merge Libraries and rearrange tests

### PR DESCRIPTION
**Pull request by mseri**

### CODE REVIEW

**Comment by mseri** [comment]
I think this should make the library releasable.
If the tests are green I will make a release by monday

**Comment by mseri** [comment]
Is the crowbar test supposed to hang? I never used it before, so I cannot compare with experience

**Comment by hannesm** [comment]
any hints / news here?

**Comment by mseri** [comment]
I am waiting to hear what is expected on the tests. Once this is good to merge I am happy to make a release

**Comment by hannesm** [comment]
AFAICT, crowbar / afl test are run infinitely, you'll have to manually terminate them (or use [bun](https://github.com/yomimono/ocaml-bun/) in a CI system to use a timeout). I'd suggest to build (i.e. check that it compiles), but not run the crowbar testing in CI.

**Comment by mseri** [comment]
Awesome, thanks. Release on the way as soon as Travis has finished its job

**Pull request merged**
