### PR TITLE
Alcotest and GIF

### PR DESCRIPTION
**Pull request by cfcs**
Current mega branch of all changes, rebased on recent master.

Supersedes https://github.com/rlepigre/ocaml-imagelib/pull/24 and https://github.com/rlepigre/ocaml-imagelib/pull/27

This is still not quite there, but it's also fairly ambitious, so maybe we should just merge it and follow up with PRs to fix various things (off the top of my head the test suite is a little bit broken, and the image resizing produces weird pixel artifacts as a result of me trying to clamp pixel offsets).

ping @yomimono :-)

### CODE REVIEW

**Comment by cfcs** [comment]
The GIF suite is still a bit messed up; afl finds 29 crashes after a few minutes, but now at least there's a framework for writing tests :-)

The main thing I'd like to ensure before we merge is that we address what we decided on here: https://github.com/rlepigre/ocaml-imagelib/pull/33#issuecomment-605227387
Namely:
- Users of the ImageLib_unix library should not be affected by my half-working attempts to deal with GIF and `resize`, but to avoid breaking existing applications should use imagemagick as before.
- The bug found by @bluddy where `close wasn't being called on the channel, leading to 0 size output files.` should be incorporated since the two git branches are hard to incorporate into each other.

**Comment by cfcs** [comment]
Okay I fixed the bug in the new decompression thing which caused parsing to just go into an infinite loop, see  https://github.com/rlepigre/ocaml-imagelib/pull/36/commits/7cbd9b4451ec44acf2d522a2c268b3e07c2537f3
So now things work with latest `decompress` \o/

The latest few commits also fix up the fuzzing/test suite skeleton a bit, and should remove the hard dependency on `afl-persistent` (which is only useful on specific ocaml compilers with the +afl flags). The fuzzer seems to work fine and generates a lot of crashes, so I think that is useful.
The test suite is not super advanced yet, so I imagine we can extend that in successive, more specific PRs.

There's still more work to be done on GIF and the resizing, but I would like to get this merged sooner rather than later since it's now a huge change set compared to `master`. As previously discussed, `imagelib-unix` does not make use of the pure GIF implementation yet, to avoid breaking things for existing users.

Merging this should address #33 and #27 (thanks @olleolleolle, sorry it took so long to get upstreamed !)

If someone has time to test that this works for them, and or/skim the diff, that' be much appreciated!
Ping @rlepigre @bluddy @yomimono

**Review by rlepigre — APPROVED** [review]
Looks good to me! :-)

**Comment by cfcs** [comment]
Sorry for my absense, I hope people had time to test :-)

**Comment by rlepigre** [comment]
Thanks a lot!

**Pull request merged**
