### PR TITLE
Dune support.

### PR DESCRIPTION
**Pull request by rlepigre**
It is probably a good idea to switch to dune although I'm not in favor of the "let's build a new fancy build system every year" policy.

### CODE REVIEW

**Comment by cfcs** [comment]
- This also means that local development pins can use the dependencies from `opam` instead of from the last release (meaning `decompress` won't be pinned to `0.7.0` anymore).

- Using Dune also allows us to have multiple opam packages in the repo so we can have a `imagelib-unix` for the imagemagick thing, and close https://github.com/rlepigre/ocaml-imagelib/issues/17

I'm merging this and will fix any problems if they occur. We should cut a release soon. :)

**Comment by rlepigre** [comment]
Great, thanks! About releases, I hear that there are ways of automating things that are well-integrated to dune. Are you familiar with the process?

**Comment by hannesm** [comment]
@rlepigre with dune-release and opam-publish it is a very smooth flow:
- edit CHANGES.md (you should get such a file, see e.g. https://github.com/mirage/mirage/blob/master/CHANGES.md) to have the newest version on top
- `dune-release tag` will create a git tag using the version number from CHANGES.md
- `dune-release distrib` will create the distribution archive (a reproducible tbz2)
- `dune-release publish` will upload the documentation to a gh-pages branch, and the release to github (using curl)
- `dune-release opam pkg` will produce an opam file ready for submitting as PR to opam-repository
- `dune release opam submit` will PR the opam file to opam-repository

:)

**Comment by rlepigre** [comment]
@hannesm that sound easy enough indeed! Thanks!

**Comment by cfcs** [comment]
@rlepigre about releases, would you consider switching to semantic versioning so we can signal things like "this release is merely a bugfix, it doesn't break the API" vs "this release has a different API, you will need to change your consumer code" ?

**Comment by rlepigre** [comment]
@cfcs I don't have any problem with that, and it is probably better to do so.

**Pull request merged**
